# Generated by Django 4.2.9 on 2024-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cookie_stands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookiestand",
            name="rating",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
